services:
  # frontend:
  #   image: odin-frontend
  #   container_name: odin-frontend
  #   # nginx exposes with port 80
  #   build:
  #     context: ./frontend/
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 5173:80
  backend:
    image: odin-backend
    container_name: odin-backend
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
# docker compose -f docker-compose.yml up --build
