version: "3.8"

services:
  frontend:
    image: odin-frontend
    container_name: odin-frontend
    # nginx exposes with port 80
    build:
      dockerfile: ./frontend/Dockerfile
    ports:
      - 5173:80
  backend:
    image: odin-backend
    container_name: odin-backend
    build:
      dockerfile: ./backend/Dockerfile
    ports:
      - 3000:3000
